"""PySpark migration of examples/customer_pipeline/legacy_pipeline.py.

Generated by the Autonomous ETL Migration Agent.

Semantic parity notes (each one is checked by the data validation stage):

* `age` is read as DoubleType, not IntegerType. The legacy pandas frame holds
  float64 because the column contains nulls, and pandas silently promotes int64
  to float64 in that case. Declaring IntegerType here would make the schema
  comparison fail.
* Rows with a null `country` are filtered out before the aggregation. pandas
  `groupby` defaults to `dropna=True` and drops them; Spark `groupBy` would keep
  null as its own group and produce one extra output row.
* `sum` is wrapped in `coalesce(..., 0.0)`. pandas returns 0.0 for a group whose
  values are all NaN; Spark returns null.
* `orderBy` uses `asc_nulls_last` to match pandas sort semantics for NaN.
* No index column is emitted. `reset_index()` is pandas bookkeeping with no
  Spark equivalent; synthesising one would break the schema comparison.
"""

from __future__ import annotations

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
)

MIN_AGE = 18

CUSTOMERS_SCHEMA = StructType(
    [
        StructField("customer_id", IntegerType(), nullable=True),
        StructField("name", StringType(), nullable=True),
        StructField("age", DoubleType(), nullable=True),
        StructField("country", StringType(), nullable=True),
        StructField("signup_date", StringType(), nullable=True),
    ]
)

ORDERS_SCHEMA = StructType(
    [
        StructField("order_id", IntegerType(), nullable=True),
        StructField("customer_id", IntegerType(), nullable=True),
        StructField("product", StringType(), nullable=True),
        StructField("quantity", IntegerType(), nullable=True),
        StructField("price", DoubleType(), nullable=True),
        StructField("order_date", StringType(), nullable=True),
    ]
)


def run(spark: SparkSession, input_dir: str, output_dir: str) -> None:
    """Compute total revenue per country for adult customers."""
    customers = spark.read.csv(
        f"{input_dir}/customers.csv", header=True, schema=CUSTOMERS_SCHEMA
    )
    orders = spark.read.csv(f"{input_dir}/orders.csv", header=True, schema=ORDERS_SCHEMA)

    # t3: null ages compare as null and are dropped by filter, matching the
    # pandas NaN >= 18 -> False behaviour.
    adults = customers.filter(F.col("age") >= F.lit(MIN_AGE))

    # t4: int * double promotes to double in both engines.
    orders_with_revenue = orders.withColumn(
        "revenue", F.col("quantity") * F.col("price")
    )

    # t5: left join keeps adults with no orders; their revenue is null.
    # `orders` measured at 159 KB by the profiler, well under the broadcast
    # threshold, so the shuffle is avoided.
    joined = adults.join(
        F.broadcast(orders_with_revenue), on="customer_id", how="left"
    )

    # t6: drop null group keys to match pandas groupby(dropna=True), then
    # coalesce so an all-null group sums to 0.0 as pandas does.
    revenue_by_country = (
        joined.filter(F.col("country").isNotNull())
        .groupBy("country")
        .agg(F.coalesce(F.sum("revenue"), F.lit(0.0)).alias("revenue"))
    )

    # t7: reset_index() has no Spark equivalent and is intentionally not emitted.
    # t8: match pandas NaN-last sort ordering.
    ordered = revenue_by_country.orderBy(F.col("country").asc_nulls_last())

    ordered.write.mode("overwrite").option("header", True).csv(
        f"{output_dir}/revenue_by_country"
    )
